spring.application.name=JavaWebService_SS9_b2s
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/db_restapi_cntt4_ss2?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456

# config jpa
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true


# C?u hình m?c log m?c ??nh cho toàn b? ?ng d?ng
logging.level.root=INFO
# C?u hình m?c log cho m?t package/class c? th?
logging.level.com.example.javawebservice_ss9_b2s=DEBUG
logging.level.org.springframework=WARN
# Ghi log ra file
logging.file.name=logs/application.log
# ??nh d?ng log trên console (có màu s?c)
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %cyan(%logger{39})
%green(%msg%n)
# ??nh d?ng log khi ghi ra file (th??ng không có màu)
# logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{39} %msg%n